version: 2

sources:
  - name: world_bank
    database: data-guest-jose-luis
    schema: world_bank_raw

    tables:
      - name: raw_data
        description: Une ligne par pays, année et indicateur.